/*
 * AnularGiros.java
 *
 * Created on 30 de octubre de 2006, 17:02
 */

package clases;

/**
 *
 * @author  Jorge
 */
public class AnularGiros extends javax.swing.JInternalFrame {
    
    /** Creates new form AnularGiros */
    public AnularGiros() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        anularGiro1 = new Paneles.AnularGiro();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setBackground(java.awt.SystemColor.window);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Panel Para Anular");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/16/Cortar.png")));
        getContentPane().add(anularGiro1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.AnularGiro anularGiro1;
    // End of variables declaration//GEN-END:variables
    
}
