/*
 * autentificar.java
 *
 * Created on 18 de octubre de 2006, 08:16 PM
 */
package clases;

import beans.Otros;
import beans.Usuario;
import beans.Horario;
import modelo.Lista;
import modelo.Mensaje;
import java.util.Date;
import java.util.List;
import beans.Tarjetas;
import java.util.logging.Level;
import java.util.logging.Logger;

public class autentificar extends javax.swing.JFrame {

    private Usuario usuario;
    private Horario horario;
    private String mensaje = "";
    private List lista;
    private Tarjetas tarjetas;

    public autentificar() {
        initComponents();
        jTNombre.setEditable(true);
        jPasswordField2.setEditable(true);
        jBEntrar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jBEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Sistema de Facturacion 4Life");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 2;
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("INGRESE POR FAVOR SU NOMBRE Y CLAVE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 2;
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 2;
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Clave:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 2;
        jPanel1.add(jLabel6, gridBagConstraints);

        jTNombre.setPreferredSize(new java.awt.Dimension(150, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 2;
        jPanel1.add(jTNombre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 2;
        jPanel1.add(jPasswordField2, gridBagConstraints);

        jBEntrar.setText("Entrar");
        jBEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEntrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 2;
        jPanel1.add(jBEntrar, gridBagConstraints);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 440, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 163, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-474)/2, (screenSize.height-189)/2, 474, 189);
    }// </editor-fold>//GEN-END:initComponents

    private void tarjetas() {

        horario = new Horario();
        Horario otro = new Horario();
        Boolean est = (false);
        otro = horario.buscar(est);
        Lista listaAnteriores = new Lista(new Otros().lista());

        for (int i = 0; i < listaAnteriores.getSize(); i++) {

            Otros b1 = (Otros) listaAnteriores.getObject(i);
            tarjetas = new Tarjetas();
            tarjetas.setNombre(b1.getNombre());
            tarjetas.setRecibi(b1.getStock());
            tarjetas.setFecha(new Date());
            tarjetas.setHorario(otro);
            tarjetas.guardar();

        }


    }

    private void jBEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEntrarActionPerformed
        jTNombre.setEditable(false);
        jPasswordField2.setEditable(false);
        jBEntrar.setEnabled(false);

        Usuario u = new Usuario();
        horario = new Horario();
        String nom = jTNombre.getText();
        String clav = jPasswordField2.getText();
        Boolean seci = false;
        Usuario usa = new Usuario();
        u = usa.bus(nom, clav);

        if (u == null) {
            Mensaje.showMensaje(this, "EL socio no existe ");
        } else {
            // Mensaje.showMensaje(this,"EL socio existe ");
            Horario otro = new Horario();
            otro = horario.bus(u, seci);
            lista = horario.lista2(seci);

            if (otro == null) {
                //Mensaje.showMensaje(this,"CUANDO ENTRA POR PRIMERA VEZ UN NUEVO USUARIO ");
                if (lista.size() == 0) {
                    //Mensaje.showMensaje(this, "si es  "+lista.size());
                    horario.setUsuario(u);
                    horario.setFechaInicio(new Date());
                    horario.setSecion(false);

                    if (horario.guardar()) {
                        Mensaje.showMensaje(this, "ya se guardo");
                        dispose();
                        tarjetas();
                        final MenuPrin pantallaPrincipal = new MenuPrin();
                        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
                        pantallaPrincipal.setBounds(0, 0, screenSize.width, screenSize.height);
                        pantallaPrincipal.setVisible(true);
                    } else {
                        Mensaje.showMensaje(this, "no guardo nada");
                    }

                } else {
                    horario = (Horario) lista.get(0);
                    Mensaje.showMensaje(this, "ERROR  " + horario.getUsuario().getNombre() + "  NO HA CERRADO EL TURNO");
                    dispose();
                }
            } else {
                Date fecha = otro.getFechaFin();
                // Mensaje.showMensaje(this,"lo encontro");
                Boolean sec = otro.getSecion();
                if (sec == false) {
                    Mensaje.showMensaje(this, "NO HA MARCADO LA HORA DE SALIDA ");
                    /*
                     * otro.setFechaFin(new Date()); otro.setSecion(true);
                     * otro.guardar();
                     */
                    final MenuPrin pantallaPrincipal = new MenuPrin();
                    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
                    pantallaPrincipal.setBounds(0, 0, screenSize.width, screenSize.height);
                    pantallaPrincipal.setVisible(true);

                } else {
                    horario = new Horario();
                    //Mensaje.showMensaje(this,"hay que crear otro TURNO");
                    horario.setUsuario(u);
                    horario.setFechaInicio(new Date());
                    horario.setSecion(false);

                    if (horario.guardar()) {
                        Mensaje.showMensaje(this, "ya se guardo");
                        tarjetas();
                        dispose();
                        final MenuPrin pantallaPrincipal = new MenuPrin();
                        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
                        pantallaPrincipal.setBounds(0, 0, screenSize.width, screenSize.height);
                        pantallaPrincipal.setVisible(true);
                    } else {
                        Mensaje.showMensaje(this, "no guardo nada");
                    }
                }

            }
    }//GEN-LAST:event_jBEntrarActionPerformed
        dispose();
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                   
                    new autentificar().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(autentificar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEntrar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTNombre;
    // End of variables declaration//GEN-END:variables
}
