/*
 * COManulargiros.java
 *
 * Created on 29 de diciembre de 2006, 18:51
 */

package clases;

/**
 *
 * @author  ANtro
 */
public class COManulargiros extends javax.swing.JInternalFrame {
    
    /** Creates new form COManulargiros */
    public COManulargiros() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        verGiroasAnulados1 = new Paneles.VerGiroasAnulados();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ver Giros Anulados");
        getContentPane().add(verGiroasAnulados1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.VerGiroasAnulados verGiroasAnulados1;
    // End of variables declaration//GEN-END:variables
    
}
