/*
 * ComBilletes.java
 *
 * Created on 10 de enero de 2007, 05:59 AM
 */

package clases;

/**
 *
 * @author  Fernando Chagaray
 */
public class ComBilletes extends javax.swing.JInternalFrame {
    
    /** Creates new form ComBilletes */
    public ComBilletes() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        billetesTrasmitter1 = new Paneles.BilletesTrasmitter();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Agregar Desglose de Billetes");
        getContentPane().add(billetesTrasmitter1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.BilletesTrasmitter billetesTrasmitter1;
    // End of variables declaration//GEN-END:variables
    
}
