/*
 * COmCieereFaltante.java
 *
 * Created on 8 de marzo de 2007, 16:16
 */

package clases;

/**
 *
 * @author  Hogar
 */
public class COmCieereFaltante extends javax.swing.JInternalFrame {
    
    /** Creates new form COmCieereFaltante */
    public COmCieereFaltante() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        panelCierreFaltante1 = new Paneles.PanelCierreFaltante();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("FALTANTE DE OTROS CIERRES");
        getContentPane().add(panelCierreFaltante1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.PanelCierreFaltante panelCierreFaltante1;
    // End of variables declaration//GEN-END:variables
    
}
