/*
 * COMcb.java
 *
 * Created on 9 de noviembre de 2006, 0:13
 */

package clases;

/**
 *
 * @author  ANtro
 */
public class COMcb extends javax.swing.JInternalFrame {
    
    /** Creates new form COMcb */
    public COMcb() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        panelCabinas1 = new Paneles.PanelCabinas();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Panel Cabinas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/16/Materia.png")));
        getContentPane().add(panelCabinas1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.PanelCabinas panelCabinas1;
    // End of variables declaration//GEN-END:variables
    
}
