/*
 * ComCobrarTarjetasCre.java
 *
 * Created on 2 de abril de 2007, 7:04
 */

package clases;

/**
 *
 * @author  Fercho
 */
public class ComCobrarTarjetasCre extends javax.swing.JInternalFrame {
    
    /** Creates new form ComCobrarTarjetasCre */
    public ComCobrarTarjetasCre() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        panelCobrarTarjetas1 = new Paneles.PanelCobrarTarjetas();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Panel Para Cobrar Tarjetas Fiadas");
        getContentPane().add(panelCobrarTarjetas1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.PanelCobrarTarjetas panelCobrarTarjetas1;
    // End of variables declaration//GEN-END:variables
    
}
