/*
 * COMCunetasXcobrar.java
 *
 * Created on 6 de noviembre de 2006, 23:31
 */

package clases;

/**
 *
 * @author  ANtro
 */
public class COMCunetasXcobrar extends javax.swing.JInternalFrame {
    
    /** Creates new form COMCunetasXcobrar */
    public COMCunetasXcobrar() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        panelCuentasporPagar1 = new Paneles.PanelCuentasporPagar();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pago de Credito (Cuentas por Cobrar)");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/16/preferences-desktop-accessibility(2).png")));
        getContentPane().add(panelCuentasporPagar1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.PanelCuentasporPagar panelCuentasporPagar1;
    // End of variables declaration//GEN-END:variables
    
}
