/*
 * ComDeuda.java
 *
 * Created on 12 de enero de 2007, 16:19
 */

package clases;

/**
 *
 * @author  Fercho
 */
public class ComDeuda extends javax.swing.JInternalFrame {
    
    /** Creates new form ComDeuda */
    public ComDeuda() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        pagarDeudas1 = new Paneles.PagarDeudas();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setForeground(java.awt.Color.white);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("PAGO DE ADQUICICIONES");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/16/Otro.png")));
        getContentPane().add(pagarDeudas1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.PagarDeudas pagarDeudas1;
    // End of variables declaration//GEN-END:variables
    
}
