/*
 * COMgirosPagados.java
 *
 * Created on 29 de diciembre de 2006, 19:43
 */

package clases;

/**
 *
 * @author  ANtro
 */
public class COMgirosPagados extends javax.swing.JInternalFrame {
    
    /** Creates new form COMgirosPagados */
    public COMgirosPagados() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        girosPagados1 = new Paneles.GirosPagados();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ver Giros Pagados");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/16/edit_f2.png")));
        getContentPane().add(girosPagados1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.GirosPagados girosPagados1;
    // End of variables declaration//GEN-END:variables
    
}
