/*
 * COMOtrosV.java
 *
 * Created on 4 de noviembre de 2006, 20:29
 */

package clases;

/**
 *
 * @author  ANtro
 */
public class COMOtrosV extends javax.swing.JInternalFrame {
    
    /** Creates new form COMOtrosV */
    public COMOtrosV() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        ingreProductos1 = new Paneles.IngreProductos();

        setBackground(java.awt.SystemColor.window);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Crear un Nuevo Producto");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/16/abrir.png")));
        getContentPane().add(ingreProductos1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.IngreProductos ingreProductos1;
    // End of variables declaration//GEN-END:variables
    
}
