/*
 * COMProvedor.java
 *
 * Created on 11 de enero de 2007, 20:29
 */

package clases;

/**
 *
 * @author  Fercho
 */
public class COMProvedor extends javax.swing.JInternalFrame {
    
    /** Creates new form COMProvedor */
    public COMProvedor() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        confiUsuarios_11 = new Paneles.ConfiUsuarios_1();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Configurar Proveedores");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/16/go-home(2).png")));
        getContentPane().add(confiUsuarios_11);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.ConfiUsuarios_1 confiUsuarios_11;
    // End of variables declaration//GEN-END:variables
    
}
