/*
 * ComVerCabinas.java
 *
 * Created on 22 de octubre de 2006, 12:20 AM
 */

package clases;

/**
 *
 * @author  Fernando Chagaray
 */
public class ComVerCabinas extends javax.swing.JInternalFrame {
    
    /** Creates new form ComVerCabinas */
    public ComVerCabinas() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        verCabinas1 = new Paneles.VerCabinas();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ver Reportes de Cabinas");
        getContentPane().add(verCabinas1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.VerCabinas verCabinas1;
    // End of variables declaration//GEN-END:variables
    
}
