/*
 * COMviajes.java
 *
 * Created on 4 de noviembre de 2006, 19:31
 */

package clases;

/**
 *
 * @author  ANtro
 */
public class COMviajes extends javax.swing.JInternalFrame {
    
    /** Creates new form COMviajes */
    public COMviajes() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        viajes1 = new Paneles.Viajes();

        setBackground(java.awt.SystemColor.window);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Panel para Ingresar Pasajes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/16/Internet.png")));
        getContentPane().add(viajes1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.Viajes viajes1;
    // End of variables declaration//GEN-END:variables
    
}
