/*
 * COMverGiros.java
 *
 * Created on 16 de diciembre de 2006, 19:49
 */

package clases;

/**
 *
 * @author  ANtro
 */
public class COMverGiros extends javax.swing.JInternalFrame {
    
    /** Creates new form COMverGiros */
    public COMverGiros() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        vergiros1 = new Paneles.Vergiros();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("VER EL REPORTE DE GIROS");
        getContentPane().add(vergiros1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.Vergiros vergiros1;
    // End of variables declaration//GEN-END:variables
    
}
