/*
 * COMVender.java
 *
 * Created on 5 de noviembre de 2006, 10:02
 */

package clases;

/**
 *
 * @author  ANtro
 */
public class COMVender extends javax.swing.JInternalFrame {
    
    /** Creates new form COMVender */
    public COMVender() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        panelOtrosS1 = new Paneles.PanelOtrosS();

        setBackground(java.awt.SystemColor.window);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Panel para realizar Ventas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/16/Usuarios.png")));
        getContentPane().add(panelOtrosS1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.PanelOtrosS panelOtrosS1;
    // End of variables declaration//GEN-END:variables
    
}
