/*
 * ComVerPagoCheque.java
 *
 * Created on 29 de octubre de 2006, 01:02 PM
 */

package clases;

/**
 *
 * @author  Fernando Chagaray
 */
public class ComVerPagoCheque extends javax.swing.JInternalFrame {
    
    /** Creates new form ComVerPagoCheque */
    public ComVerPagoCheque() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        verPagosCheques1 = new Paneles.VerPagosCheques();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reporte de Pagos con Cheques");
        getContentPane().add(verPagosCheques1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.VerPagosCheques verPagosCheques1;
    // End of variables declaration//GEN-END:variables
    
}
