/*
 * ComVerVideo.java
 *
 * Created on 22 de octubre de 2006, 10:23 PM
 */

package clases;

/**
 *
 * @author  Fernando Chagaray
 */
public class ComVerVideo extends javax.swing.JInternalFrame {
    
    /** Creates new form ComVerVideo */
    public ComVerVideo() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        verVideoCon1 = new Paneles.VerVideoCon();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reporte de Video Conferencias");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/16/Pensum.png")));
        getContentPane().add(verVideoCon1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.VerVideoCon verVideoCon1;
    // End of variables declaration//GEN-END:variables
    
}
