/*
 * ComVerGirosOfi.java
 *
 * Created on 21 de octubre de 2006, 08:59 PM
 */

package clases;

/**
 *
 * @author  Fernando Chagaray
 */
public class ComVerGirosOfi extends javax.swing.JInternalFrame {
    
    /** Creates new form ComVerGirosOfi */
    public ComVerGirosOfi() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        vergirosOficina1 = new Paneles.VergirosOficina();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ver Giros de Oficina");
        getContentPane().add(vergirosOficina1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.VergirosOficina vergirosOficina1;
    // End of variables declaration//GEN-END:variables
    
}
