/*
 * COMvergiroremplazado.java
 *
 * Created on 29 de diciembre de 2006, 16:34
 */

package clases;

/**
 *
 * @author  ANtro
 */
public class COMvergiroremplazado extends javax.swing.JInternalFrame {
    
    /** Creates new form COMvergiroremplazado */
    public COMvergiroremplazado() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        vergirosRemplazados1 = new Paneles.VergirosRemplazados();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ver Giros Remplazados");
        getContentPane().add(vergirosRemplazados1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.VergirosRemplazados vergirosRemplazados1;
    // End of variables declaration//GEN-END:variables
    
}
