/*
 * ConCierre1.java
 *
 * Created on 30 de enero de 2007, 01:29 AM
 */

package clases;

/**
 *
 * @author  Fernando Chagaray
 */
public class ConCierre1 extends javax.swing.JInternalFrame {
    
    /** Creates new form ConCierre1 */
    public ConCierre1() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        verCaja11 = new Paneles.VerCaja1();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle(" CAJA DE L.G. MONEY TRANSMITTER");
        getContentPane().add(verCaja11, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.VerCaja1 verCaja11;
    // End of variables declaration//GEN-END:variables
    
}
