/*
 * Confagencia.java
 *
 * Created on 26 de octubre de 2006, 21:31
 */

package clases;

/**
 *
 * @author  Jorge
 */
public class Confagencia extends javax.swing.JInternalFrame {
    
    /** Creates new form Confagencia */
    public Confagencia() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        cinfiAgencias1 = new Paneles.CinfiAgencias();

        setBackground(java.awt.SystemColor.window);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Panel Para Configurar Agencias");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/16/Asistencia.png")));
        getContentPane().add(cinfiAgencias1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.CinfiAgencias cinfiAgencias1;
    // End of variables declaration//GEN-END:variables
    
}
