/*
 * ConfigurarGiros.java
 *
 * Created on 25 de octubre de 2006, 21:54
 */

package clases;

/**
 *
 * @author  ANtro
 */
public class ConfigurarGiros extends javax.swing.JInternalFrame {
    
    /** Creates new form ConfigurarGiros */
    public ConfigurarGiros() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        miercoles1 = new clases.miercoles();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Panel Para Configurar Giros");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/16/Accesos.png")));
        getContentPane().add(miercoles1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private clases.miercoles miercoles1;
    // End of variables declaration//GEN-END:variables
    
}
