/*
 * FindeTurno.java
 *
 * Created on 1 de febrero de 2007, 09:47 AM
 */

package clases;

/**
 *
 * @author  Fernando Chagaray
 */
public class FindeTurno extends javax.swing.JInternalFrame {
    
    /** Creates new form FindeTurno */
    public FindeTurno() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        finTurno1 = new Paneles.FinTurno();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cierre Total de Caja");
        getContentPane().add(finTurno1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.FinTurno finTurno1;
    // End of variables declaration//GEN-END:variables
    
}
