/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frm_accesosDialog.java
 *
 * Created on 14/07/2008, 11:59:12 AM
 */
package clases;

import beans.Horario;
import beans.Otros;
import beans.Tarjetas;
import beans.Usuario;
import hibernate.Configuracion;
import java.awt.event.KeyEvent;
import java.io.UnsupportedEncodingException;
import java.util.Date;
import java.util.List;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import modelo.Lista;
import modelo.Mensaje;

/**
 *
 * @author Richitar
 */
public class frm_accesosDialog extends javax.swing.JDialog {

    private Usuario usuario;
    private Horario horario;
    private String mensaje = "";
    private List lista;
    private Tarjetas tarjetas;

    public frm_accesosDialog() {
        initComponents();
//        this.principal=prin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        bt_ingresar = new javax.swing.JButton();
        bt_salir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingreso al sistema");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Usuario"));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setText("Login :");

        jTNombre.setColumns(10);
        jTNombre.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTNombre.setSelectionEnd(10);
        jTNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTNombreFocusGained(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setText("Clave :");

        jPasswordField2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusGained(evt);
            }
        });
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_ingresar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bt_ingresar.setText("INGRESAR");
        bt_ingresar.setPreferredSize(new java.awt.Dimension(117, 25));
        bt_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ingresarActionPerformed(evt);
            }
        });
        jPanel6.add(bt_ingresar);

        bt_salir.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bt_salir.setText("CANCELAR");
        bt_salir.setPreferredSize(new java.awt.Dimension(117, 25));
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });
        bt_salir.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                bt_salirAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel6.add(bt_salir);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Escoja una opción"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Ventas");
        jPanel2.add(jRadioButton1, new java.awt.GridBagConstraints());

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Reportes");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTNombreFocusGained
        jTNombre.selectAll();
    }//GEN-LAST:event_jTNombreFocusGained

    private void jPasswordField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusGained
        jPasswordField2.selectAll();
    }//GEN-LAST:event_jPasswordField2FocusGained

    private void jPasswordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                mt_ingresar();
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(frm_accesosDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jPasswordField2KeyPressed

    private void bt_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ingresarActionPerformed
        
        
        if (jRadioButton1.isSelected()) {
            try {
                mt_ingresar();
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(frm_accesosDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (jRadioButton2.isSelected()) {
            mt_ingresarReportes();
        }
        
    }//GEN-LAST:event_bt_ingresarActionPerformed

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        Configuracion.cerrar();
        this.dispose();
    }//GEN-LAST:event_bt_salirActionPerformed

    private void bt_salirAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_bt_salirAncestorAdded
    }//GEN-LAST:event_bt_salirAncestorAdded

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        System.out.println("jejejejeje");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    public void mt_ingresarReportes(){

        jTNombre.setEditable(false);
        jPasswordField2.setEditable(false);


        Usuario u = new Usuario();
        horario = new Horario();
        String nom = jTNombre.getText();
        String clav = jPasswordField2.getText();
        Boolean seci = false;
        Usuario usa = new Usuario();
        u = usa.bus(nom, clav);

        if (u == null) {
            Mensaje.showMensaje(this, "EL socio no existe ");
        } else {
            this.dispose();
            java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
            MenuPrinReportes pantallaPrincipal = new MenuPrinReportes();
            pantallaPrincipal.setExtendedState(JFrame.MAXIMIZED_BOTH);
            pantallaPrincipal.setBounds(0, 0, screenSize.width, screenSize.height);
            pantallaPrincipal.setVisible(true);
        }
    }
    
    public void mt_ingresar() throws UnsupportedEncodingException {
        jTNombre.setEditable(false);
        jPasswordField2.setEditable(false);


        Usuario u = new Usuario();
        horario = new Horario();
        String nom = jTNombre.getText();
        String clav = jPasswordField2.getText();
        Boolean seci = false;
        Usuario usa = new Usuario();
        u = usa.bus(nom, clav);

        if (u == null) {
            Mensaje.showMensaje(this, "EL socio no existe ");
        } else {
            // Mensaje.showMensaje(this,"EL socio existe ");
            Horario otro = new Horario();
            otro = horario.bus(u, seci);
            lista = horario.lista2(seci);

            if (otro == null) {
                //Mensaje.showMensaje(this,"CUANDO ENTRA POR PRIMERA VEZ UN NUEVO USUARIO ");
                if (lista.size() == 0) {
                    //Mensaje.showMensaje(this, "si es  "+lista.size());
                    horario.setUsuario(u);
                    horario.setFechaInicio(new Date());
                    horario.setSecion(false);

                    if (horario.guardar()) {
                        Mensaje.showMensaje(this, "ya se guardo");
                        this.dispose();
                        tarjetas();
                        iniciarMenuPrincipal();
                    } else {
                        Mensaje.showMensaje(this, "no guardo nada");
                    }

                } else {
                    horario = (Horario) lista.get(0);
                    Mensaje.showMensaje(this, "ERROR  " + horario.getUsuario().getNombre() + "  NO HA CERRADO EL TURNO");
                    this.dispose();
                }
            } else {
                Date fecha = otro.getFechaFin();
                // Mensaje.showMensaje(this,"lo encontro");
                Boolean sec = otro.getSecion();
                if (sec == false) {
                    Mensaje.showMensaje(this, "NO HA MARCADO LA HORA DE SALIDA ");
                    /*
                     * otro.setFechaFin(new Date()); otro.setSecion(true);
                     * otro.guardar();
                     */
                    this.dispose();
                    iniciarMenuPrincipal();

                } else {
                    horario = new Horario();
                    //Mensaje.showMensaje(this,"hay que crear otro TURNO");
                    horario.setUsuario(u);
                    horario.setFechaInicio(new Date());
                    horario.setSecion(false);

                    if (horario.guardar()) {
                        Mensaje.showMensaje(this, "ya se guardo");
                        tarjetas();
                        this.dispose();
                        iniciarMenuPrincipal();
                    } else {
                        Mensaje.showMensaje(this, "no guardo nada");
                    }
                }

            }
        }
    }

    public void iniciarMenuPrincipal() {
        final PanSplash panSplash = new PanSplash(new javax.swing.JFrame());
        SwingUtilities.invokeLater(new Runnable() {

            public void run() {
                panSplash.showSplashScreen();
            }
        });

        final MenuPrin pantallaPrincipal = new MenuPrin();
        SwingUtilities.invokeLater(new Runnable() {

            public void run() {
                panSplash.hideSplash();
                java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
                pantallaPrincipal.setExtendedState(JFrame.MAXIMIZED_BOTH);
                pantallaPrincipal.setBounds(0, 0, screenSize.width, screenSize.height);
                pantallaPrincipal.setVisible(true);

            }
        });
    }

    private void tarjetas() {

        horario = new Horario();
        Horario otro = new Horario();
        Boolean est = (false);
        otro = horario.buscar(est);
        Lista listaAnteriores = new Lista(new Otros().lista());

        for (int i = 0; i < listaAnteriores.getSize(); i++) {

            Otros b1 = (Otros) listaAnteriores.getObject(i);
            tarjetas = new Tarjetas();
            tarjetas.setNombre(b1.getNombre());
            tarjetas.setRecibi(b1.getStock());
            tarjetas.setFecha(new Date());
            tarjetas.setHorario(otro);
            tarjetas.guardar();
        }
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frm_accesosDialog().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ingresar;
    private javax.swing.JButton bt_salir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTNombre;
    // End of variables declaration//GEN-END:variables
}
