/*
 * PanMantenimiento.java
 *
 * Created on 5 de marzo de 2006, 03:47 PM
 */

package clases;



/**
 *
 * @author  Edison
 */
public class PanMantenimiento extends javax.swing.JPanel {
    
    public static final int VACIO=1;
    
    private int tipo;
    
    /** Creates new form PanMantenimiento */
    public PanMantenimiento() {
        initComponents();
    }
    
    /**
     * 
     * @param b 
     */
    public void setActiva(boolean b){
        getBtnAceptar().setEnabled(b);
        getBtnCancelar().setEnabled(b);
        getBtnNuevo().setEnabled(!b);
        getBtnBorrar().setEnabled(!b);
        getBtnEditar().setEnabled(!b);
    }
    
     public void setNuevo(boolean b){
        btnNuevo.setVisible(b);
    }
    
    public void setEditar(boolean b){
        btnEditar.setVisible(b);
    }
    
    public void setAceptar(boolean b){
        btnAceptar.setVisible(b);
    }
    
    public void setBorrar(boolean b){
        btnBorrar.setVisible(b);
    }
    
    public void setCancelar(boolean b){
        btnCancelar.setVisible(b);
    }
    
   
    /**
     * 
     * @param tipo 
     */
    
    
    public void setEstado(int tipo){
        setTipo(tipo);
        switch (getTipo()){
            case VACIO:
                getBtnBorrar().setEnabled(false);
                getBtnEditar().setEnabled(false);
            break;
        }
    }

    /**
     * 
     * @return 
     */
    public javax.swing.JButton getBtnAceptar() {
        return btnAceptar;
    }

    /**
     * 
     * @param btnAceptar 
     */
    public void setBtnAceptar(javax.swing.JButton btnAceptar) {
        this.btnAceptar = btnAceptar;
    }

    /**
     * 
     * @return 
     */
    public javax.swing.JButton getBtnBorrar() {
        return btnBorrar;
    }

    /**
     * 
     * @param btnBorrar 
     */
    public void setBtnBorrar(javax.swing.JButton btnBorrar) {
        this.btnBorrar = btnBorrar;
    }

   

    /**
     * 
     * @return 
     */
    public javax.swing.JButton getBtnCancelar() {
        return btnCancelar;
    }

    /**
     * 
     * @param btnCancelar 
     */
    public void setBtnCancelar(javax.swing.JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    /**
     * 
     * @return 
     */
    public javax.swing.JButton getBtnEditar() {
        return btnEditar;
    }

    /**
     * 
     * @param btnEditar 
     */
    public void setBtnEditar(javax.swing.JButton btnEditar) {
        this.btnEditar = btnEditar;
    }

   

    /**
     * 
     * @return 
     */
    public javax.swing.JButton getBtnNuevo() {
        return btnNuevo;
    }

    /**
     * 
     * @param btnNuevo 
     */
    public void setBtnNuevo(javax.swing.JButton btnNuevo) {
        this.btnNuevo = btnNuevo;
    }

    /**
     * 
     * @return 
     */
    public int getTipo() {
        return tipo;
    }

    /**
     * 
     * @param tipo 
     */
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setBackground(java.awt.SystemColor.window);
        setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11)); // NOI18N
        setPreferredSize(new java.awt.Dimension(416, 40));

        btnNuevo.setBackground(java.awt.SystemColor.window);
        btnNuevo.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/nuevo.png"))); // NOI18N
        btnNuevo.setMnemonic('N');
        btnNuevo.setText("Nuevo");
        btnNuevo.setToolTipText("Nuevo Registro");
        btnNuevo.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNuevo.setNextFocusableComponent(btnEditar);
        add(btnNuevo);

        btnEditar.setBackground(java.awt.SystemColor.window);
        btnEditar.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/editar.png"))); // NOI18N
        btnEditar.setMnemonic('E');
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Editar Registro");
        btnEditar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        add(btnEditar);

        btnAceptar.setBackground(java.awt.SystemColor.window);
        btnAceptar.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11)); // NOI18N
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/guardar.png"))); // NOI18N
        btnAceptar.setMnemonic('A');
        btnAceptar.setText("Aceptar");
        btnAceptar.setToolTipText("Aceptar");
        btnAceptar.setEnabled(false);
        btnAceptar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        add(btnAceptar);

        btnBorrar.setBackground(java.awt.SystemColor.window);
        btnBorrar.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11)); // NOI18N
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/Borrar.png"))); // NOI18N
        btnBorrar.setMnemonic('B');
        btnBorrar.setText("Borrar");
        btnBorrar.setToolTipText("Borrar Registro");
        btnBorrar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        add(btnBorrar);

        btnCancelar.setBackground(java.awt.SystemColor.window);
        btnCancelar.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/Cancelar.png"))); // NOI18N
        btnCancelar.setMnemonic('C');
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Aceptar");
        btnCancelar.setEnabled(false);
        btnCancelar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        add(btnCancelar);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNuevo;
    // End of variables declaration//GEN-END:variables
    
}
