/*
 * PantallaPrincipal.java
 *
 * Created on 8 de agosto de 2006, 11:57 AM
 */

package clases;

import javax.swing.SwingUtilities;

/**
 *
 * @author  Edison
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    
    
    
    
    /** Creates new form PantallaPrincipal */
    public PantallaPrincipal() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        panSuperior = new javax.swing.JPanel();
        panSocio = new javax.swing.JPanel();
        jLabelNombreGrup1 = new javax.swing.JLabel();
        jLabelCedula1 = new javax.swing.JLabel();
        jLabelNombre1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabelApellido1 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabelCivil1 = new javax.swing.JLabel();
        jLabelCreditopendiente1 = new javax.swing.JLabel();
        jLabelSubtitulo6 = new javax.swing.JLabel();
        datFechaIngreso = new org.jdesktop.swingx.JXDatePicker();
        cboAgencia = new javax.swing.JComboBox();
        jLabelLonjitud = new javax.swing.JLabel();
        jLabelNombre2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblFechaIngreso = new javax.swing.JLabel();
        txtNeto = new javax.swing.JTextField();
        txtAgente = new javax.swing.JTextField();
        panNavegador1 = new clases.PanNavegador();
        panMantenimiento1 = new clases.PanMantenimiento();
        panInferior = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panProduccion = new javax.swing.JPanel();
        lblYearProduccion = new javax.swing.JLabel();
        cboYear = new org.jdesktop.swingx.JXComboBox();
        jLabel2 = new javax.swing.JLabel();
        cboCafe = new org.jdesktop.swingx.JXComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCategoriaO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        panAportacionExtra = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cboYearExtra = new org.jdesktop.swingx.JXComboBox();
        jLabel12 = new javax.swing.JLabel();
        datFechaExtra = new org.jdesktop.swingx.JXDatePicker();
        jLabel13 = new javax.swing.JLabel();
        cboAporteExtra = new org.jdesktop.swingx.JXComboBox();
        jLabel14 = new javax.swing.JLabel();
        panAportacionFija = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        cboYearFija = new org.jdesktop.swingx.JXComboBox();
        label1 = new java.awt.Label();
        cboDesde = new org.jdesktop.swingx.JXComboBox();
        label2 = new java.awt.Label();
        cboHasta = new org.jdesktop.swingx.JXComboBox();
        jLabel17 = new javax.swing.JLabel();
        datFechaFija = new org.jdesktop.swingx.JXDatePicker();
        jLabel18 = new javax.swing.JLabel();
        cboAporteFija = new org.jdesktop.swingx.JXComboBox();
        panIngresoABodega = new javax.swing.JPanel();
        jLabelNombre6 = new javax.swing.JLabel();
        txtSaldePendiente = new javax.swing.JTextField();
        jLabelCreditopendiente3 = new javax.swing.JLabel();
        txtComprobante = new javax.swing.JTextField();
        jLabelNombre3 = new javax.swing.JLabel();
        txtBultos = new javax.swing.JTextField();
        jLabelNombre5 = new javax.swing.JLabel();
        txtTotalenDolares = new javax.swing.JTextField();
        jLabelNombre4 = new javax.swing.JLabel();
        jLabelNombre7 = new javax.swing.JLabel();
        jLabelNombre21 = new javax.swing.JLabel();
        jLabelNombre20 = new javax.swing.JLabel();
        jLabelNombre22 = new javax.swing.JLabel();
        txtTipoCafe = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        panSuperior.setLayout(new java.awt.BorderLayout());

        panSocio.setLayout(new java.awt.GridBagLayout());

        jLabelNombreGrup1.setText("Nombre ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panSocio.add(jLabelNombreGrup1, gridBagConstraints);

        jLabelCedula1.setText("Nombre de la Agencia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 9);
        panSocio.add(jLabelCedula1, gridBagConstraints);

        jLabelNombre1.setText("Codigo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panSocio.add(jLabelNombre1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panSocio.add(txtNombre, gridBagConstraints);

        jLabelApellido1.setText("Agente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panSocio.add(jLabelApellido1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panSocio.add(txtTotal, gridBagConstraints);

        jLabelCivil1.setText("Total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panSocio.add(jLabelCivil1, gridBagConstraints);

        jLabelCreditopendiente1.setFont(new java.awt.Font("Arial Black", 0, 12));
        jLabelCreditopendiente1.setForeground(new java.awt.Color(204, 0, 51));
        jLabelCreditopendiente1.setText("INGRESO DE  GIROS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panSocio.add(jLabelCreditopendiente1, gridBagConstraints);

        jLabelSubtitulo6.setFont(new java.awt.Font("Bodoni MT", 1, 12));
        jLabelSubtitulo6.setForeground(new java.awt.Color(0, 0, 204));
        jLabelSubtitulo6.setText("DATOS DE LA CAJERA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panSocio.add(jLabelSubtitulo6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        panSocio.add(datFechaIngreso, gridBagConstraints);

        cboAgencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Soltero", "Casado", "Divorciado", "Otros" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panSocio.add(cboAgencia, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panSocio.add(jLabelLonjitud, gridBagConstraints);

        jLabelNombre2.setText("Neto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panSocio.add(jLabelNombre2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panSocio.add(txtCodigo, gridBagConstraints);

        lblFechaIngreso.setText("Fecha de Ingreso");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panSocio.add(lblFechaIngreso, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panSocio.add(txtNeto, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panSocio.add(txtAgente, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        panSocio.add(panNavegador1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        panSocio.add(panMantenimiento1, gridBagConstraints);

        panSuperior.add(panSocio, java.awt.BorderLayout.CENTER);

        jSplitPane1.setTopComponent(panSuperior);

        panInferior.setLayout(new java.awt.BorderLayout());

        panProduccion.setLayout(new java.awt.GridBagLayout());

        lblYearProduccion.setText("A\u00f1o ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panProduccion.add(lblYearProduccion, gridBagConstraints);

        cboYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panProduccion.add(cboYear, gridBagConstraints);

        jLabel2.setText("Categoria ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panProduccion.add(jLabel2, gridBagConstraints);

        cboCafe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panProduccion.add(cboCafe, gridBagConstraints);

        jLabel4.setText("Valor estimado ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panProduccion.add(jLabel4, gridBagConstraints);

        jLabel7.setText("Observacion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panProduccion.add(jLabel7, gridBagConstraints);

        txtCategoriaO.setColumns(25);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panProduccion.add(txtCategoriaO, gridBagConstraints);

        jLabel3.setText("Saldo Pendiente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panProduccion.add(jLabel3, gridBagConstraints);

        jTabbedPane1.addTab("Produccion", panProduccion);

        panAportacionExtra.setLayout(new java.awt.GridBagLayout());

        jLabel11.setText("A\u00f1o ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panAportacionExtra.add(jLabel11, gridBagConstraints);

        cboYearExtra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panAportacionExtra.add(cboYearExtra, gridBagConstraints);

        jLabel12.setText("Fecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panAportacionExtra.add(jLabel12, gridBagConstraints);

        datFechaExtra.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panAportacionExtra.add(datFechaExtra, gridBagConstraints);

        jLabel13.setText("Aporte");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panAportacionExtra.add(jLabel13, gridBagConstraints);

        cboAporteExtra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboAporteExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAporteExtraActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panAportacionExtra.add(cboAporteExtra, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panAportacionExtra.add(jLabel14, gridBagConstraints);

        jTabbedPane1.addTab("Aportacion Extra", panAportacionExtra);

        panAportacionFija.setLayout(new java.awt.GridBagLayout());

        jLabel16.setText("A\u00f1o ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panAportacionFija.add(jLabel16, gridBagConstraints);

        cboYearFija.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panAportacionFija.add(cboYearFija, gridBagConstraints);

        label1.setText("Desde");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panAportacionFija.add(label1, gridBagConstraints);

        cboDesde.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cboDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDesdeActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panAportacionFija.add(cboDesde, gridBagConstraints);

        label2.setName("Hasta");
        label2.setText("Hasta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panAportacionFija.add(label2, gridBagConstraints);

        cboHasta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cboHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboHastaActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panAportacionFija.add(cboHasta, gridBagConstraints);

        jLabel17.setText("Fecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panAportacionFija.add(jLabel17, gridBagConstraints);

        datFechaFija.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panAportacionFija.add(datFechaFija, gridBagConstraints);

        jLabel18.setText("Aporte");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panAportacionFija.add(jLabel18, gridBagConstraints);

        cboAporteFija.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboAporteFija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAporteFijaActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panAportacionFija.add(cboAporteFija, gridBagConstraints);

        jTabbedPane1.addTab("Aportaci\u00f3n Fija", panAportacionFija);

        panIngresoABodega.setLayout(new java.awt.GridBagLayout());

        jLabelNombre6.setText("Saldo pendiente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panIngresoABodega.add(jLabelNombre6, gridBagConstraints);

        txtSaldePendiente.setColumns(25);
        txtSaldePendiente.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panIngresoABodega.add(txtSaldePendiente, gridBagConstraints);

        jLabelCreditopendiente3.setText("# Comprobante ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panIngresoABodega.add(jLabelCreditopendiente3, gridBagConstraints);

        txtComprobante.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtComprobante.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panIngresoABodega.add(txtComprobante, gridBagConstraints);

        jLabelNombre3.setText("# de Bultos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panIngresoABodega.add(jLabelNombre3, gridBagConstraints);

        txtBultos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBultos.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panIngresoABodega.add(txtBultos, gridBagConstraints);

        jLabelNombre5.setText("Total $");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panIngresoABodega.add(jLabelNombre5, gridBagConstraints);

        txtTotalenDolares.setEditable(false);
        txtTotalenDolares.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalenDolares.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panIngresoABodega.add(txtTotalenDolares, gridBagConstraints);

        jLabelNombre4.setText("Saldo pendiente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panIngresoABodega.add(jLabelNombre4, gridBagConstraints);

        jLabelNombre7.setText("Humedad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panIngresoABodega.add(jLabelNombre7, gridBagConstraints);

        jLabelNombre21.setText("Humedad al 12%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panIngresoABodega.add(jLabelNombre21, gridBagConstraints);

        jLabelNombre20.setText("Calidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panIngresoABodega.add(jLabelNombre20, gridBagConstraints);

        jLabelNombre22.setText("Tipo de Cafe");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panIngresoABodega.add(jLabelNombre22, gridBagConstraints);

        txtTipoCafe.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panIngresoABodega.add(txtTipoCafe, gridBagConstraints);

        btnCalcular.setText("Calcular");
        btnCalcular.setEnabled(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        panIngresoABodega.add(btnCalcular, gridBagConstraints);

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        panIngresoABodega.add(btnGuardar, gridBagConstraints);

        jTabbedPane1.addTab("Ingreso a bodega", panIngresoABodega);

        panInferior.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(panInferior);

        jScrollPane1.setViewportView(jSplitPane1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
// TODO add your handling code here:
//        Comprobante c = new Comprobante();
//        c.setBultos(Float.parseFloat(txtBultos.getText()));
//        c.setBultosReales(Float.parseFloat(txtHumedad12.getText()));
//        c.setFecha(new Date());
//        c.setHumedad(Float.parseFloat(txtHumedad.getText()));
//        c.setIdComprobante(Integer.parseInt(txtComprobante.getText()));
//        c.setProduccion(produccion);
//        c.setSocio(socio);
//        c.setValor(Float.parseFloat(txtTotalenDolares.getText()));
//        c.setCategoria(categoria);
//        if(c.guardar()){
//            produccion.setSaldo(Float.parseFloat(txtSaldo.getText()));
//            produccion.actualizar();
//            setPanelSocio();
//            Mensaje.showMensaje(this,"Ingreso completo");
//            reporte(c);
//        }else
//            Mensaje.showError(this,"El Comprobante ya existe","Error");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
// TODO add your handling code here:
//        Float nBultos=Float.parseFloat(txtBultos.getText());
//        Float humedad=Float.parseFloat(txtHumedad.getText());
//        //     Float nBultosReales=nBultos*humedad/100f;
//        Float nBultosReales=nBultos*((1f-humedad/100f)/0.88f)/1.25f;
//        Float saldo=nBultosReales*produccion.getCafe().getValor()*0.15f;
//        Float saldoFinal = produccion.getSaldo()-nBultosReales;
//        txtHumedad12.setText(""+nBultosReales);
//        txtTotalenDolares.setText(""+saldo);
//        txtSaldo.setText(""+saldoFinal);
//        txtCalidaa.setText("C");
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void cboAporteFijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAporteFijaActionPerformed
// TODO add your handling code here:
//        setConfiguracion();
    }//GEN-LAST:event_cboAporteFijaActionPerformed

    private void cboHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboHastaActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_cboHastaActionPerformed

    private void cboDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDesdeActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_cboDesdeActionPerformed

    private void cboAporteExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAporteExtraActionPerformed
// TODO add your handling code here:
//        setConfiguracion();
    }//GEN-LAST:event_cboAporteExtraActionPerformed

    private void setPanelBlanco(){
        
        txtCodigo.setText("");
        txtNombre.setText("");
       
        panAportacionExtra.setEnabled(false);
        panAportacionFija.setEnabled(false);
        panIngresoABodega.setEnabled(false);
        panProduccion.setEnabled(false);
    }
    
    private void setPanelSocio(){
        
    }
    
      public static void main(String args[]) {
        
    /*    final PanSplash panSplash = new PanSplash(new javax.swing.JFrame());
        SwingUtilities.invokeLater(new Runnable() {
	    public void run() {
		panSplash.showSplashScreen();
	    }
	});
        
        final PantallaPrincipal pantallaPrincipal= new PantallaPrincipal();
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                panSplash.hideSplash();
                java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();                
                pantallaPrincipal.setBounds(0, 0, screenSize.width, screenSize.height);
                pantallaPrincipal.setVisible(true);
                
            }
        });*/
     //new PantallaPrincipal().setVisible(true);
     //dispose();
      new PantallaPrincipal().setVisible(true);
    }  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cboAgencia;
    private org.jdesktop.swingx.JXComboBox cboAporteExtra;
    private org.jdesktop.swingx.JXComboBox cboAporteFija;
    private org.jdesktop.swingx.JXComboBox cboCafe;
    private org.jdesktop.swingx.JXComboBox cboDesde;
    private org.jdesktop.swingx.JXComboBox cboHasta;
    private org.jdesktop.swingx.JXComboBox cboYear;
    private org.jdesktop.swingx.JXComboBox cboYearExtra;
    private org.jdesktop.swingx.JXComboBox cboYearFija;
    private org.jdesktop.swingx.JXDatePicker datFechaExtra;
    private org.jdesktop.swingx.JXDatePicker datFechaFija;
    private org.jdesktop.swingx.JXDatePicker datFechaIngreso;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelApellido1;
    private javax.swing.JLabel jLabelCedula1;
    private javax.swing.JLabel jLabelCivil1;
    private javax.swing.JLabel jLabelCreditopendiente1;
    private javax.swing.JLabel jLabelCreditopendiente3;
    private javax.swing.JLabel jLabelLonjitud;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNombre2;
    private javax.swing.JLabel jLabelNombre20;
    private javax.swing.JLabel jLabelNombre21;
    private javax.swing.JLabel jLabelNombre22;
    private javax.swing.JLabel jLabelNombre3;
    private javax.swing.JLabel jLabelNombre4;
    private javax.swing.JLabel jLabelNombre5;
    private javax.swing.JLabel jLabelNombre6;
    private javax.swing.JLabel jLabelNombre7;
    private javax.swing.JLabel jLabelNombreGrup1;
    private javax.swing.JLabel jLabelSubtitulo6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JLabel lblFechaIngreso;
    private javax.swing.JLabel lblYearProduccion;
    private javax.swing.JPanel panAportacionExtra;
    private javax.swing.JPanel panAportacionFija;
    private javax.swing.JPanel panInferior;
    private javax.swing.JPanel panIngresoABodega;
    private clases.PanMantenimiento panMantenimiento1;
    private clases.PanNavegador panNavegador1;
    private javax.swing.JPanel panProduccion;
    private javax.swing.JPanel panSocio;
    private javax.swing.JPanel panSuperior;
    private javax.swing.JTextField txtAgente;
    private javax.swing.JTextField txtBultos;
    private javax.swing.JTextField txtCategoriaO;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtComprobante;
    private javax.swing.JTextField txtNeto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSaldePendiente;
    private javax.swing.JTextField txtTipoCafe;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalenDolares;
    // End of variables declaration//GEN-END:variables
    
}
