/*
 * RemplazarG.java
 *
 * Created on 26 de octubre de 2006, 15:23
 */

package clases;

/**
 *
 * @author  ANtro
 */
public class RemplazarG extends javax.swing.JInternalFrame {
    
    /** Creates new form RemplazarG */
    public RemplazarG() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        remplazoG2 = new Paneles.RemplazoG();

        setBackground(java.awt.SystemColor.window);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Panel Para Remplazar Giros");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/16/Warning.png")));
        getContentPane().add(remplazoG2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.RemplazoG remplazoG2;
    // End of variables declaration//GEN-END:variables
    
}
