/*
 * AdelantoDeposito.java
 *
 * Created on 2 de febrero de 2007, 0:15
 */

package clases;

/**
 *
 * @author  Fercho
 */
public class AdelantoDeposito extends javax.swing.JInternalFrame {
    
    /** Creates new form AdelantoDeposito */
    public AdelantoDeposito() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        panelCheques_11 = new Paneles.PanelCheques_1();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Adelantos de Depositos");
        getContentPane().add(panelCheques_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 780, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.PanelCheques_1 panelCheques_11;
    // End of variables declaration//GEN-END:variables
    
}
