/*
 * autentificar.java
 *
 * Created on 18 de octubre de 2006, 08:16 PM
 */

package clases;

import beans.Otros;
import beans.Usuario;
import beans.Horario;
import java.awt.event.KeyEvent;
import modelo.Lista;
import modelo.Mensaje;
import java.util.Date;
import java.util.List;
import beans.Tarjetas;

public class autentificar extends javax.swing.JFrame {
    
   private Usuario usuario;
   private Horario horario;
   private String mensaje="";
   private List lista; 
   private Tarjetas tarjetas;
   
    public autentificar() {
        initComponents();
        jTNombre.setEditable(true);
        jPasswordField1.setEditable(true);
        jBEntrar.setEnabled(true);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jlClave = new javax.swing.JLabel();
        jBEntrar = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jPanel1.setBackground(java.awt.SystemColor.activeCaptionText);
        jPanel1.setName("VERIFICAR");
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jLabel2.setBackground(java.awt.SystemColor.textHighlight);
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel2.setForeground(java.awt.SystemColor.textHighlight);
        jLabel2.setText("PROGRAMA DE GESTION OFIMATICA DE LG TRAVEL");

        jLabel1.setBackground(java.awt.SystemColor.textHighlight);
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13));
        jLabel1.setForeground(java.awt.SystemColor.textHighlight);
        jLabel1.setText("INGRESE POR FAVOR SU NOMBRE Y CLAVE");

        jLNombre.setText("Nombre");

        jlClave.setText("Clave");

        jBEntrar.setText("Entrar");
        jBEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEntrarActionPerformed(evt);
            }
        });

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(36, 36, 36)
                        .add(jLabel2))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(25, 25, 25)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 378, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(200, 200, 200)
                        .add(jBEntrar))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(122, 122, 122)
                                .add(jlClave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(121, 121, 121)
                                .add(jLNombre)))
                        .add(24, 24, 24)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jTNombre)
                            .add(jPasswordField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(56, 56, 56)
                .add(jLabel2)
                .add(28, 28, 28)
                .add(jLabel1)
                .add(20, 20, 20)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLNombre)
                    .add(jTNombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(8, 8, 8)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlClave)
                    .add(jPasswordField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(5, 5, 5)
                .add(jBEntrar))
        );
        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-461)/2, (screenSize.height-302)/2, 461, 302);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed

        
        
        
    }//GEN-LAST:event_jPanel1KeyPressed

    private void tarjetas(){
        
      horario=new Horario();
                   Horario otro = new Horario();
                   Boolean est=(false);
                   otro=horario.buscar(est);
       Lista listaAnteriores =new Lista(new Otros().lista());
       
       for(int i=0;i<listaAnteriores.getSize();i++){
           
                   Otros b1=(Otros) listaAnteriores.getObject(i);
                   tarjetas = new Tarjetas();
                   tarjetas.setNombre(b1.getNombre());
                   tarjetas.setRecibi(b1.getStock());
                   tarjetas.setFecha(new Date());
                   tarjetas.setHorario(otro);
                   tarjetas.guardar();
                   
                   }
        
        
    }
    
    
    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
// TODO add your handling code here:
      
    if(evt.getKeyCode()== KeyEvent.VK_ENTER){
    jTNombre.setEditable(false);
    jPasswordField1.setEditable(false);
    jBEntrar.setEnabled(false);
    
    Usuario u= new Usuario();
    horario = new Horario();
    String nom = jTNombre.getText();
    String clav =jPasswordField1.getText();
    
    Boolean seci=false;
    Usuario usa= new Usuario();
    u=usa.bus(nom,clav);
  
   if (u==null){
       Mensaje.showMensaje(this,"EL socio no existe ");
        }else{
    // Mensaje.showMensaje(this,"EL socio existe ");
               Horario otro = new Horario();
               otro=horario.bus(u,seci);
               lista = horario.lista2(seci);
               
                 if(otro==null){
                                 //Mensaje.showMensaje(this,"CUANDO ENTRA POR PRIMERA VEZ UN NUEVO USUARIO ");
                                if (lista.size()==0){
                                    // Mensaje.showMensaje(this, "si es  "+lista.size());
                                     horario.setUsuario(u);
                                     horario.setFechaInicio(new Date());
                                     horario.setSecion(false);
                                     if (horario.guardar()){
                                     Mensaje.showMensaje(this,"ya se guardo");
                                     tarjetas();
                                     dispose();
                                             final MenuPrin pantallaPrincipal= new MenuPrin();
                                             java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();                
                                             pantallaPrincipal.setBounds(0, 0, screenSize.width, screenSize.height);
                                             pantallaPrincipal.setVisible(true);
                                                        }else{
                                 Mensaje.showMensaje(this,"no guardo nada");
                                                                  }     
                                
                                }else{
                                        horario=(Horario) lista.get(0);
                                        Mensaje.showMensaje(this, "ERROR  "+horario.getUsuario().getNombre()+"  NO HA CERRADO EL TURNO");
                                        dispose();      
                                }
                            
                              }else{
                                Date fecha=otro.getFechaFin();
                                Boolean sec=otro.getSecion();
                               // Mensaje.showMensaje(this,"lo encontro");
                                if(sec==false){
                                                Mensaje.showMensaje(this,"NO HA MARCADO LA HORA DE SALIDA ");
                                                /*
                                                  otro.setFechaFin(new Date());
                                                  otro.setSecion(true);
                                                  otro.guardar();
                                                 */ 
                                             final MenuPrin pantallaPrincipal= new MenuPrin();
                                             java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();                
                                             pantallaPrincipal.setBounds(0, 0, screenSize.width, screenSize.height);
                                             pantallaPrincipal.setVisible(true);
                                                  
                                               }else{
                                                    horario = new Horario();
                                                    //Mensaje.showMensaje(this,"hay que crear otro TURNO");
                                                    horario.setUsuario(u);
                                                    horario.setFechaInicio(new Date());
                                                    horario.setSecion(false);
                                    
                                                     if (horario.guardar()){
                                             Mensaje.showMensaje(this,"ya se guardo");
                                             dispose();
                                             tarjetas();
                                             final MenuPrin pantallaPrincipal= new MenuPrin();
                                             java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();                
                                             pantallaPrincipal.setBounds(0, 0, screenSize.width, screenSize.height);
                                             pantallaPrincipal.setVisible(true);
                                                     }else{
                                             Mensaje.showMensaje(this,"no guardo nada");
                                                                  }
                                                      }
   
                                }
   
    }                                        
      dispose();
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
// TODO add your handling code here:
        
                    
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jBEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEntrarActionPerformed
    jTNombre.setEditable(false);
    jPasswordField1.setEditable(false);
    jBEntrar.setEnabled(false);
    
    Usuario u= new Usuario();
    horario = new Horario();
    String nom = jTNombre.getText();
    String clav =jPasswordField1.getText();
    Boolean seci=false;
    Usuario usa= new Usuario();
    u=usa.bus(nom,clav);
    
        if (u==null){
       Mensaje.showMensaje(this,"EL socio no existe ");
        }else{
      // Mensaje.showMensaje(this,"EL socio existe ");
               Horario otro = new Horario();
               otro=horario.bus(u,seci);
               lista = horario.lista2(seci);
   
                 if(otro==null){
                                 //Mensaje.showMensaje(this,"CUANDO ENTRA POR PRIMERA VEZ UN NUEVO USUARIO ");
                                if (lista.size()==0){
                                 //Mensaje.showMensaje(this, "si es  "+lista.size());
                                 horario.setUsuario(u);
                                 horario.setFechaInicio(new Date());
                                 horario.setSecion(false);
                                 
                                 if (horario.guardar()){
                                 Mensaje.showMensaje(this,"ya se guardo");
                                 dispose();
                                 tarjetas();
                                             final MenuPrin pantallaPrincipal= new MenuPrin();
                                             java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();                
                                             pantallaPrincipal.setBounds(0, 0, screenSize.width, screenSize.height);
                                             pantallaPrincipal.setVisible(true);
                                                        }else{
                                 Mensaje.showMensaje(this,"no guardo nada");
                                                                  }
                                 
                                }else{
                                        horario=(Horario) lista.get(0);
                                        Mensaje.showMensaje(this, "ERROR  "+horario.getUsuario().getNombre()+"  NO HA CERRADO EL TURNO");
                                        dispose();      
                                }
                              }else{
                                Date fecha=otro.getFechaFin();
                               // Mensaje.showMensaje(this,"lo encontro");
                                Boolean sec=otro.getSecion();
                                if(sec==false){
                                                Mensaje.showMensaje(this,"NO HA MARCADO LA HORA DE SALIDA ");
                                                /*
                                                  otro.setFechaFin(new Date());
                                                  otro.setSecion(true);
                                                  otro.guardar();
                                                 */ 
                                             final MenuPrin pantallaPrincipal= new MenuPrin();
                                             java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();                
                                             pantallaPrincipal.setBounds(0, 0, screenSize.width, screenSize.height);
                                             pantallaPrincipal.setVisible(true);
                                                  
                                               }else{
                                                    horario = new Horario();
                                                    //Mensaje.showMensaje(this,"hay que crear otro TURNO");
                                                    horario.setUsuario(u);
                                                    horario.setFechaInicio(new Date());
                                                    horario.setSecion(false);
                                    
                                                     if (horario.guardar()){
                                             Mensaje.showMensaje(this,"ya se guardo");
                                             tarjetas();
                                             dispose();
                                             final MenuPrin pantallaPrincipal= new MenuPrin();
                                             java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();                
                                             pantallaPrincipal.setBounds(0, 0, screenSize.width, screenSize.height);
                                             pantallaPrincipal.setVisible(true);
                                                     }else{
                                             Mensaje.showMensaje(this,"no guardo nada");
                                                                  }
                                                      }
   
                                }
   
    }//GEN-LAST:event_jBEntrarActionPerformed
      dispose();
    }
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new autentificar().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEntrar;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JLabel jlClave;
    // End of variables declaration//GEN-END:variables
    
}
