/*
 * COMAnuPq.java
 *
 * Created on 7 de noviembre de 2006, 2:47
 */

package clases;

/**
 *
 * @author  ANtro
 */
public class COMAnuPq extends javax.swing.JInternalFrame {
    
    /** Creates new form COMAnuPq */
    public COMAnuPq() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        devolverP1 = new Paneles.DevolverP();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Panael para Anular Paquetes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/16/Cortar.png")));
        getContentPane().add(devolverP1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.DevolverP devolverP1;
    // End of variables declaration//GEN-END:variables
    
}
