/*
 * COMAgreUnidades.java
 *
 * Created on 23 de diciembre de 2006, 18:28
 */

package clases;

/**
 *
 * @author  ANtro
 */
public class COMAgreUnidades extends javax.swing.JInternalFrame {
    
    /** Creates new form COMAgreUnidades */
    public COMAgreUnidades() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        ingreProductos_11 = new Paneles.IngreProductos_1();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Agregar Unidades a los Productos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/16/Profesor.png")));
        getContentPane().add(ingreProductos_11, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.IngreProductos_1 ingreProductos_11;
    // End of variables declaration//GEN-END:variables
    
}
