/*
 * COMChequeProtestado.java
 *
 * Created on 21 de octubre de 2006, 02:40 PM
 */

package clases;

/**
 *
 * @author  Fernando Chagaray
 */
public class COMChequeProtestado extends javax.swing.JInternalFrame {
    
    /** Creates new form COMChequeProtestado */
    public COMChequeProtestado() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        chequeProtestado1 = new Paneles.ChequeProtestado();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Protestar un Cheque");
        getContentPane().add(chequeProtestado1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.ChequeProtestado chequeProtestado1;
    // End of variables declaration//GEN-END:variables
    
}
