/*
 * ComDarCredito.java
 *
 * Created on 23 de octubre de 2006, 12:11 AM
 */

package clases;

/**
 *
 * @author  Fernando Chagaray
 */
public class ComDarCredito extends javax.swing.JInternalFrame {
    
    /** Creates new form ComDarCredito */
    public ComDarCredito() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        verPagosCreditos1 = new Paneles.VerPagosCreditos();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reporte Creditos Pagados");
        getContentPane().add(verPagosCreditos1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.VerPagosCreditos verPagosCreditos1;
    // End of variables declaration//GEN-END:variables
    
}
