/*
 * COMnuevoU.java
 *
 * Created on 9 de diciembre de 2006, 20:33
 */

package clases;

/**
 *
 * @author  ANtro
 */
public class COMnuevoU extends javax.swing.JInternalFrame {
    
    /** Creates new form COMnuevoU */
    public COMnuevoU() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        nuevoU1 = new Paneles.nuevoU();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Entrar como Nuevo Usuario");
        getContentPane().add(nuevoU1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.nuevoU nuevoU1;
    // End of variables declaration//GEN-END:variables
    
}
