/*
 * COMprasOficina.java
 *
 * Created on 7 de noviembre de 2006, 16:50
 */

package clases;

/**
 *
 * @author  ANtro
 */
public class COMprasOficina extends javax.swing.JInternalFrame {
    
    /** Creates new form COMprasOficina */
    public COMprasOficina() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        panelCompras1 = new Paneles.PanelCompras();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().add(panelCompras1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.PanelCompras panelCompras1;
    // End of variables declaration//GEN-END:variables
    
}
