/*
 * ComVerDarCreditos.java
 *
 * Created on 22 de octubre de 2006, 11:29 PM
 */

package clases;

/**
 *
 * @author  Fernando Chagaray
 */
public class ComVerDarCreditos extends javax.swing.JInternalFrame {
    
    /** Creates new form ComVerDarCreditos */
    public ComVerDarCreditos() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        verDarCreditos1 = new Paneles.VerDarCreditos();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reporte de Creditos Dados");
        getContentPane().add(verDarCreditos1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.VerDarCreditos verDarCreditos1;
    // End of variables declaration//GEN-END:variables
    
}
