/*
 * ComVerFlores.java
 *
 * Created on 21 de octubre de 2006, 11:17 PM
 */

package clases;

/**
 *
 * @author  Fernando Chagaray
 */
public class ComVerFlores extends javax.swing.JInternalFrame {
    
    /** Creates new form ComVerFlores */
    public ComVerFlores() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        verFlores1 = new Paneles.VerFlores();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ver Las Flores Vendidas");
        getContentPane().add(verFlores1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.VerFlores verFlores1;
    // End of variables declaration//GEN-END:variables
    
}
