/*
 * COMvc.java
 *
 * Created on 23 de noviembre de 2006, 0:03
 */

package clases;

/**
 *
 * @author  ANtro
 */
public class COMvc extends javax.swing.JInternalFrame {
    
    /** Creates new form COMvc */
    public COMvc() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        panelVideo1 = new Paneles.PanelVideo();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Panel de Video Conferencia");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/16/Pensum.png")));
        getContentPane().add(panelVideo1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.PanelVideo panelVideo1;
    // End of variables declaration//GEN-END:variables
    
}
