/*
 * ConfiUser.java
 *
 * Created on 27 de octubre de 2006, 10:41
 */

package clases;

/**
 *
 * @author  Jorge
 */
public class ConfiUser extends javax.swing.JInternalFrame {
    
    /** Creates new form ConfiUser */
    public ConfiUser() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        confiUsuarios1 = new Paneles.ConfiUsuarios();

        setBackground(java.awt.SystemColor.window);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Configurar Usuarios");
        getContentPane().add(confiUsuarios1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.ConfiUsuarios confiUsuarios1;
    // End of variables declaration//GEN-END:variables
    
}
