/*
 * ConVerVentas.java
 *
 * Created on 22 de octubre de 2006, 10:56 PM
 */

package clases;

/**
 *
 * @author  Fernando Chagaray
 */
public class ConVerVentas extends javax.swing.JInternalFrame {
    
    /** Creates new form ConVerVentas */
    public ConVerVentas() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        verVentas1 = new Paneles.VerVentas();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reporte de Ventas Diarias");
        getContentPane().add(verVentas1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.VerVentas verVentas1;
    // End of variables declaration//GEN-END:variables
    
}
