/*
 * Pagosdegiros.java
 *
 * Created on 31 de octubre de 2006, 15:57
 */

package clases;

/**
 *
 * @author  ANtro
 */
public class Pagosdegiros extends javax.swing.JInternalFrame {
    
    /** Creates new form Pagosdegiros */
    public Pagosdegiros() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        pagarGiro1 = new Paneles.PagarGiro();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Panel para pagar Giros");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/16/edit_f2.png")));
        getContentPane().add(pagarGiro1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.PagarGiro pagarGiro1;
    // End of variables declaration//GEN-END:variables
    
}
