/*
 * VerChequePro.java
 *
 * Created on 29 de enero de 2007, 11:03 PM
 */

package clases;

/**
 *
 * @author  Fernando Chagaray
 */
public class VerChequePro extends javax.swing.JInternalFrame {
    
    /** Creates new form VerChequePro */
    public VerChequePro() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        verChequesProtestados1 = new Paneles.VerChequesProtestados();

        setBackground(java.awt.SystemColor.activeCaptionText);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reporte de Cheques Protestatdos");
        getContentPane().add(verChequesProtestados1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.VerChequesProtestados verChequesProtestados1;
    // End of variables declaration//GEN-END:variables
    
}
