/*
 * Vercierrres.java
 *
 * Created on 13 de marzo de 2007, 14:29
 */

package clases;

/**
 *
 * @author  Hogar
 */
public class Vercierrres extends javax.swing.JInternalFrame {
    
    /** Creates new form Vercierrres */
    public Vercierrres() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        finTurno_11 = new Paneles.FinTurno_1();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pantalla para ver Cieeres Anteriores");
        getContentPane().add(finTurno_11, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.FinTurno_1 finTurno_11;
    // End of variables declaration//GEN-END:variables
    
}
